### ISSUE TITLE
0.9.5 - Underscore 1.3.3 not working with Google Closure r1810

### ISSUE THREAD

**Issue by lltyk** [lltyk/tapestry-wro4j#5]
The fix is in Google Closure r1947, which is not released.

Workarounds include using UglifyJSMinimizer or YuiJSMinimizer instead.

Relevant issues:
https://github.com/documentcloud/underscore/issues/579
http://code.google.com/p/closure-compiler/issues/detail?id=718

**Comment by jochenberger** [comment]
This should be fixed now that we're on a recent version of wro4j and closure-compiler.

**Comment by lltyk** [comment]
Fixed in 0.9.8.
